import { useEffect, useState, useMemo } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import {
  Download,
  AlertTriangle,
  CheckCircle,
  Info,
  FileText,
  Eye,
  Printer,
  X,
  ChevronDown,
  ChevronRight,
} from "lucide-react";
import AppLayout from "@/components/AppLayout";
import jsPDF from "jspdf";
import autoTable, { type Color } from "jspdf-autotable";

import { DiseaseInfoCard } from "@/components/disease/DiseaseInfoCard";
import { useDiseaseInsights } from "@/hooks/useDiseaseInsights";
import { getConditionName, getConditionNameForInsights } from "@/data/conditionMap";
import { predictWithAILabTools } from "@/integrations/ailabtools/client";

// --------------------------- Types -----------------------------
interface Prediction {
  label: string;
  confidence: number;
}
interface MalignantRisk {
  probability: number;
  threshold: number;
  riskLabel: string;
}
interface ModelInfo {
  architecture: string;
  version: string;
  num_models?: number;
}
interface ProfileData {
  id: string;
  full_name?: string | null;
  age?: number | null;
  phone?: string | null;
  skin_type?: string | null;
  allergies?: string | null;
  notes?: string | null;
}

type RiskLevel = "low" | "moderate" | "high";

const decideRiskLevel = (p: number): RiskLevel => (p > 0.7 ? "high" : p > 0.3 ? "moderate" : "low");
const formatPercent = (v: number, digits = 1) => `${(v * 100).toFixed(digits)}%`;
const riskBadgeVariant = (risk: RiskLevel) =>
  risk === "high" ? "destructive" : risk === "moderate" ? "secondary" : "default";
const professionalDisclaimer =
  "AI-Assisted Dermatological Assessment: This document is NOT an official medical diagnosis nor a substitute for professional clinical evaluation. It was generated by an AI system and should only be used as supplementary information to support a licensed dermatologist’s examination. Do not initiate, discontinue, or modify any treatment solely based on this report.";
const interpretConfidence = (c: number) => {
  if (c >= 0.7) return "High AI confidence.";
  if (c >= 0.3) return "Moderate AI confidence.";
  return "Low AI confidence. Clinical evaluation essential.";
};

// Brand colors for PDF styling (typed to jsPDF-AutoTable Color)
const BRAND_BLUE: Color = [14, 165, 233]; // #0EA5E9
const BRAND_TEXT_DARK_RGB: [number, number, number] = [15, 23, 42]; // #0F172A
const TEXT_BODY_RGB: [number, number, number] = [17, 24, 39]; // #111827
const LINE_GRAY: Color = [226, 232, 240]; // #E2E8F0
const ZEBRA: Color = [248, 250, 252]; // #F8FAFC

// --------------------- Main Component --------------------------
const Report = () => {
  const navigate = useNavigate();
  const { id } = useParams();

  const [loading, setLoading] = useState(true);
  const [analyzing, setAnalyzing] = useState(false);
  const [predictions, setPredictions] = useState<Prediction[]>([]);
  const [malignantRisk, setMalignantRisk] = useState<MalignantRisk | null>(null);
  const [modelInfo, setModelInfo] = useState<ModelInfo | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [savedId, setSavedId] = useState<string | null>(null);
  const [profile, setProfile] = useState<ProfileData | null>(null);
  const [showPreview, setShowPreview] = useState(false);
  const [imageMeta, setImageMeta] = useState<{ filename: string; sizeKB: number; capturedAt: string } | null>(null);

  // UI toggles
  const [showAllPreds, setShowAllPreds] = useState(false);

  const generatedDate = useMemo(() => new Date(), []);

  // Top condition (raw and display)
  const topRaw = predictions.length ? predictions[0].label : undefined;
  const topDisplay = topRaw ? getConditionName(topRaw) : "—";

  // Use mapped name for insights if available (else raw)
  const insightQuery = topRaw ? getConditionNameForInsights(topRaw) : undefined;

  // Hook for insights
  const { info, loadingInfo, errorInfo } = useDiseaseInsights(insightQuery);

  useEffect(() => {
    (async () => {
      const {
        data: { session },
      } = await supabase.auth.getSession();
      if (!session) {
        navigate("/auth");
        return;
      }

      await loadProfile(session.user.id);

      if (id && id !== "mock-id") {
        await loadStoredDiagnosis(id);
        setLoading(false);
        return;
      }

      const fileDataStr = sessionStorage.getItem("uploadedFile");
      if (!fileDataStr) {
        toast.error("Please upload an image first.");
        navigate("/upload");
        return;
      }

      try {
        const parsed = JSON.parse(fileDataStr);
        const sizeKB = parsed.size ? parsed.size / 1024 : 0;
        setImageMeta({
          filename: parsed.name || "uploaded_image.jpg",
          sizeKB: Number(sizeKB.toFixed(1)),
          capturedAt: new Date().toLocaleString(),
        });
      } catch {
        setImageMeta(null);
      }

      setLoading(false);
      await performPrediction(fileDataStr);
    })();
  }, [navigate, id]);

  async function loadProfile(userId: string) {
    try {
      const sb: any = supabase;
      const { data } = await sb.from("profiles").select("*").eq("id", userId).maybeSingle();
      if (data) setProfile(data);
    } catch {
      setProfile(null);
    }
  }

  async function loadStoredDiagnosis(diagnosisId: string) {
    try {
      const sb: any = supabase;
      const { data, error } = await sb.from("diagnoses").select("*").eq("id", diagnosisId).single();
      if (error) throw error;
      if (!data) {
        toast.error("Report not found");
        navigate("/history");
        return;
      }
      setPredictions((data.top_predictions ?? []).map((p: any) => ({
        label: p.label_name,
        confidence: p.confidence,
      })));
      setMalignantRisk({
        probability: data.malignant_probability,
        threshold: 0.5,
        riskLabel: data.malignant_flag ? "High risk" : "Low risk",
      });
      setModelInfo({
        architecture: data.model_version?.startsWith("ailabtools") ? "Cloud AI Engine" : "AI Engine",
        version: data.model_version || "ai-engine",
      });
      setSavedId(diagnosisId);
    } catch {
      toast.error("Failed to load diagnosis");
      navigate("/history");
    }
  }

  async function saveDiagnosis(payload: {
    top1_label: string;
    top1_confidence: number;
    top_predictions: any[];
    malignant_probability: number;
    malignant_flag: boolean;
    model_version?: string;
  }) {
    try {
      const { data: userData } = await supabase.auth.getUser();
      const user = userData?.user;
      if (!user) return null;
      const risk_level: RiskLevel = decideRiskLevel(payload.malignant_probability);
      const sb: any = supabase;
      const { data, error } = await sb
        .from("diagnoses")
        .insert({
          user_id: user.id,
          top_condition: payload.top1_label,
          top_confidence: payload.top1_confidence,
          top_predictions: payload.top_predictions,
          malignant_probability: payload.malignant_probability,
          malignant_flag: payload.malignant_flag,
          risk_level,
          model_version: payload.model_version ?? "ai-engine",
        })
        .select()
        .single();
      if (error) throw error;
      return data?.id ?? null;
    } catch {
      toast.error("Failed to save diagnosis to history");
      return null;
    }
  }

  async function performPrediction(fileDataStr: string) {
    setAnalyzing(true);
    setError(null);
    const USE_VENDOR = String(import.meta.env.VITE_USE_AILABTOOLS || "false").toLowerCase() === "true";

    try {
      const fileData = JSON.parse(fileDataStr);

      let result:
        | {
            top1_label: string;
            top1_confidence: number;
            top_predictions: Array<{ label_name: string; confidence: number }>;
            malignant_probability: number;
            malignant_flag: boolean;
            model_version?: string;
          }
        | null = null;

      if (USE_VENDOR) {
        result = await predictWithAILabTools(fileData.data);
      } else {
        // Legacy fallback (if still enabled)
        const blob = await (await fetch(fileData.data)).blob();
        const formData = new FormData();
        formData.append("file", blob, fileData.name);
        const API_URL = import.meta.env.VITE_API_URL || "http://localhost:8080";
        const response = await fetch(`${API_URL}/predict`, { method: "POST", body: formData });
        if (!response.ok) {
          let msg = "Prediction failed";
          try {
            const ed = await response.json();
            msg = ed.detail || ed.message || msg;
          } catch {
            msg = (await response.text()) || msg;
          }
          throw new Error(msg);
        }
        const data = await response.json();
        if (!data.success) throw new Error("API returned unsuccessful response");
        result = {
          top1_label: data.top1_label,
          top1_confidence: data.top1_confidence,
          top_predictions: data.top_predictions,
          malignant_probability: data.malignant_probability,
          malignant_flag: data.malignant_flag,
          model_version: data.model_version,
        };
      }

      if (!result) throw new Error("No prediction result");

      setPredictions((result.top_predictions ?? []).map((p: any) => ({
        label: p.label_name || p.label || "Unknown",
        confidence: p.confidence || 0,
      })));
      setMalignantRisk({
        probability: result.malignant_probability || 0,
        threshold: 0.5,
        riskLabel: result.malignant_flag ? "High risk" : "Low risk",
      });
      setModelInfo({
        architecture: USE_VENDOR ? "Cloud AI Engine" : "AI Engine",
        version: result.model_version || (USE_VENDOR ? "ailabapi" : "ai-engine"),
      });

      const insertedId = await saveDiagnosis({
        top1_label: result.top1_label,
        top1_confidence: result.top1_confidence,
        top_predictions: result.top_predictions,
        malignant_probability: result.malignant_probability,
        malignant_flag: result.malignant_flag,
        model_version: result.model_version || (USE_VENDOR ? "ailabapi" : "ai-engine"),
      });

      if (insertedId) {
        setSavedId(insertedId);
        window.history.replaceState(null, "", `/report/${insertedId}`);
      }

      toast.success("Analysis complete");
    } catch (err: any) {
      let errorMessage = "Failed to analyze image.\n\n";
      if (
        !String(import.meta.env.VITE_USE_AILABTOOLS || "")
          .toLowerCase()
          .includes("true") &&
        err.name === "TypeError" &&
        String(err.message).includes("fetch")
      ) {
        const apiUrl = import.meta.env.VITE_API_URL || "http://localhost:8080";
        errorMessage = `Cannot connect to legacy API server at ${apiUrl}

Please ensure:
1. Legacy API (if still used) is running.
2. API is accessible at ${apiUrl}
3. Check the API terminal for errors
4. Verify .env has: VITE_API_URL="${apiUrl}"`;
      } else {
        errorMessage += err.message || "Unknown error occurred.";
      }
      setError(errorMessage);
      toast.error("Analysis failed");
    } finally {
      setAnalyzing(false);
    }
  }

  // --------------------- PDF Generation -----------------------
  function generatePDF() {
    if (!predictions.length || !malignantRisk) {
      toast.error("Report incomplete - cannot export yet.");
      return;
    }

    const doc = new jsPDF("p", "pt", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();
    const left = 40;
    let y = 50;
    const gap = 16;

    // Brand header bar
    doc.setFillColor(BRAND_BLUE[0], BRAND_BLUE[1], BRAND_BLUE[2]);
    doc.rect(0, 0, pageWidth, 50, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("DermaVision — Clinical Skin Assessment", left, 32);

    // Reset to dark text for content
    doc.setTextColor(BRAND_TEXT_DARK_RGB[0], BRAND_TEXT_DARK_RGB[1], BRAND_TEXT_DARK_RGB[2]);
    y = 70;

    const h1 = (t: string) => {
      doc.setTextColor(BRAND_TEXT_DARK_RGB[0], BRAND_TEXT_DARK_RGB[1], BRAND_TEXT_DARK_RGB[2]);
      doc.setFont("helvetica", "bold"); doc.setFontSize(14); doc.text(t, left, y);
      // underline rule
      doc.setDrawColor(BRAND_BLUE[0], BRAND_BLUE[1], BRAND_BLUE[2]);
      doc.setLineWidth(1);
      doc.line(left, y + 4, left + 230, y + 4);
      y += 22;
    };
    const h2 = (t: string) => {
      doc.setTextColor(BRAND_TEXT_DARK_RGB[0], BRAND_TEXT_DARK_RGB[1], BRAND_TEXT_DARK_RGB[2]);
      doc.setFont("helvetica", "bold"); doc.setFontSize(12); doc.text(t, left, y); y += 18;
    };
    const p = (t: string) => {
      doc.setTextColor(TEXT_BODY_RGB[0], TEXT_BODY_RGB[1], TEXT_BODY_RGB[2]);
      doc.setFont("helvetica", "normal"); doc.setFontSize(10);
      const lines = doc.splitTextToSize(t, 520);
      lines.forEach((l: string) => { doc.text(l, left, y); y += 12; });
      y += 4;
    };

    // Meta line
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(`Report ID: ${savedId ?? id ?? "new"}    Date: ${generatedDate.toLocaleString()}`, left, y);
    y += gap;

    h1("Patient");
    autoTable(doc, {
      startY: y,
      theme: "grid",
      head: [["Field", "Value"]],
      body: [
        ["Full Name", profile?.full_name || "Not provided"],
        ["Age", profile?.age ? String(profile.age) : "Not provided"],
        ["Allergies", profile?.allergies || "None reported"],
      ],
      styles: {
        fontSize: 9,
        cellPadding: 6,
        textColor: TEXT_BODY_RGB as Color,
        lineColor: LINE_GRAY,
      },
      headStyles: {
        fillColor: BRAND_BLUE,
        textColor: [255, 255, 255],
        fontStyle: "bold",
      },
      columnStyles: { 0: { cellWidth: 120 } },
    });
    y = (doc as any).lastAutoTable.finalY + 14;

    h1("Assessment Summary");
    const topName = topDisplay;
    doc.setTextColor(BRAND_TEXT_DARK_RGB[0], BRAND_TEXT_DARK_RGB[1], BRAND_TEXT_DARK_RGB[2]);
    doc.setFont("helvetica", "bold"); doc.setFontSize(12); doc.text(`Top Condition: ${topName}`, left, y); y += 16;
    doc.setFont("helvetica", "normal"); doc.setFontSize(10);
    doc.setTextColor(TEXT_BODY_RGB[0], TEXT_BODY_RGB[1], TEXT_BODY_RGB[2]);
    doc.text(
      `Risk indicator: ${formatPercent(malignantRisk.probability, 1)} (${decideRiskLevel(
        malignantRisk.probability
      )} risk)`,
      left,
      y
    );
    y += gap;

    const topList = predictions.slice(0, 3).map((p) => [
      getConditionName(p.label),
      formatPercent(p.confidence, 1),
      interpretConfidence(p.confidence),
    ]);
    autoTable(doc, {
      startY: y,
      theme: "striped",
      head: [["Condition", "Confidence", "Interpretation"]],
      body: topList,
      styles: {
        fontSize: 9,
        cellPadding: 6,
        textColor: TEXT_BODY_RGB as Color,
      },
      headStyles: {
        fillColor: BRAND_BLUE,
        textColor: [255, 255, 255],
        fontStyle: "bold",
      },
      alternateRowStyles: { fillColor: ZEBRA },
      columnStyles: {
        0: { cellWidth: 130 },
        1: { cellWidth: 85, halign: "left" },
        2: { cellWidth: "auto" },
      },
    });
    y = (doc as any).lastAutoTable.finalY + 14;

    h1("Capture");
    autoTable(doc, {
      startY: y,
      theme: "grid",
      head: [["Field", "Value"]],
      body: [
        ["Image file", imageMeta?.filename || "N/A"],
        ["Timestamp", imageMeta?.capturedAt || generatedDate.toLocaleString()],
      ],
      styles: {
        fontSize: 9,
        cellPadding: 6,
        textColor: TEXT_BODY_RGB as Color,
        lineColor: LINE_GRAY,
      },
      headStyles: {
        fillColor: BRAND_BLUE,
        textColor: [255, 255, 255],
        fontStyle: "bold",
      },
      columnStyles: { 0: { cellWidth: 120 } },
    });
    y = (doc as any).lastAutoTable.finalY + 14;

    h1("Next Steps");
    p(
      "• Visit a licensed dermatologist for clinical examination.\n• Monitor changes with periodic photos.\n• Do not start or stop treatment based solely on this AI report."
    );

    h1("Disclaimer");
    p(professionalDisclaimer);

    // Sanitize and use user's name in filename: "User_name skin report.pdf"
    const safeName =
      (profile?.full_name?.trim() || "User")
        .replace(/[\\/:*?\"<>|]+/g, "")   // remove invalid filename chars
        .replace(/\s+/g, " ")             // normalize spaces
        .trim();

    doc.save(`${safeName} skin report.pdf`);
    toast.success("PDF downloaded.");
  }

  // -------------------- Preview Modal --------------------
  const PreviewModal = () => {
    if (!showPreview) return null;
    return (
      <div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4">
        <div className="bg-background w-full max-w-3xl rounded-lg shadow-lg overflow-hidden animate-in fade-in-50">
          <div className="flex justify-between items-center p-4 border-b">
            <h3 className="font-semibold text-lg">Report Preview (Short)</h3>
            <Button variant="ghost" size="icon" onClick={() => setShowPreview(false)}>
              <X className="h-5 w-5" />
            </Button>
          </div>
          <div className="p-6 max-h-[70vh] overflow-y-auto space-y-6 text-sm">
            <Alert className="border-warning bg-warning/10">
              <AlertTriangle className="h-4 w-4 text-warning" />
              <AlertDescription className="text-xs leading-relaxed font-medium">
                {professionalDisclaimer}
              </AlertDescription>
            </Alert>

            <section className="space-y-2">
              <h4 className="font-semibold text-base">Patient</h4>
              <div className="grid grid-cols-2 gap-x-6 gap-y-2">
                <div>
                  <span className="text-muted-foreground">Full Name:</span>{" "}
                  <span className="font-medium">{profile?.full_name || "Not provided"}</span>
                </div>
                <div>
                  <span className="text-muted-foreground">Age:</span>{" "}
                  <span className="font-medium">{profile?.age ?? "Not provided"}</span>
                </div>
                <div className="col-span-2">
                  <span className="text-muted-foreground">Allergies:</span>{" "}
                  <span className="font-medium">{profile?.allergies || "None reported"}</span>
                </div>
              </div>
            </section>

            <section className="space-y-2">
              <h4 className="font-semibold text-base">Assessment Summary</h4>
              <div className="flex items-center justify-between bg-muted/40 p-3 rounded-md">
                <div className="font-medium">{topDisplay}</div>
                {malignantRisk && (
                  <Badge variant={riskBadgeVariant(decideRiskLevel(malignantRisk.probability))} className="capitalize">
                    {decideRiskLevel(malignantRisk.probability)} risk
                  </Badge>
                )}
              </div>
              {malignantRisk && (
                <div className="text-xs text-muted-foreground">
                  Risk indicator:{" "}
                  <span className="font-medium">
                    {formatPercent(malignantRisk.probability, 1)}
                  </span>
                </div>
              )}
            </section>

            <section className="space-y-2">
              <h4 className="font-semibold text-base">Top Conditions</h4>
              <div className="space-y-3">
                {predictions.slice(0, 3).map((p, i) => (
                  <div key={i} className="border rounded-md p-3 bg-muted/30">
                    <div className="flex justify-between">
                      <span className="font-medium">{getConditionName(p.label)}</span>
                      <Badge variant={i === 0 ? "default" : "secondary"}>{formatPercent(p.confidence, 1)}</Badge>
                    </div>
                    <p className="text-xs text-muted-foreground">{interpretConfidence(p.confidence)}</p>
                  </div>
                ))}
              </div>
            </section>

            <section className="space-y-1 text-[10px] text-muted-foreground">
              <div>Image file: {imageMeta?.filename || "N/A"}</div>
              <div>Captured: {imageMeta?.capturedAt || generatedDate.toLocaleString()}</div>
            </section>
          </div>
          <div className="flex justify-end gap-3 p-4 border-t">
            <Button variant="outline" onClick={() => window.print()}>
              <Printer className="h-4 w-4 mr-1" />
              Print
            </Button>
            <Button onClick={generatePDF}>
              <Download className="h-4 w-4 mr-1" />
              Download PDF
            </Button>
            <Button variant="ghost" onClick={() => setShowPreview(false)}>
              Close
            </Button>
          </div>
        </div>
      </div>
    );
  };

  // -------------------- Loading/Error States ------------------
  if (loading) {
    return (
      <AppLayout>
        <div className="flex items-center justify-center h-screen">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
        </div>
      </AppLayout>
    );
  }

  if (analyzing) {
    return (
      <AppLayout>
        <div className="flex flex-col items-center justify-center h-screen gap-4">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
          <p className="text-lg font-medium">Analyzing your image...</p>
          <p className="text-sm text-muted-foreground">Generating your summary…</p>
        </div>
      </AppLayout>
    );
  }

  if (error) {
    return (
      <AppLayout>
        <div className="flex flex-col items-center justify-center h-screen gap-4 px-4">
          <AlertTriangle className="h-16 w-16 text-destructive" />
          <h2 className="text-2xl font-bold">Analysis Failed</h2>
          <pre className="text-muted-foreground text-center max-w-md whitespace-pre-wrap text-sm bg-muted p-4 rounded-lg">
            {error}
          </pre>
          <div className="flex gap-4">
            <Button onClick={() => navigate("/upload")} variant="outline">
              Upload New Image
            </Button>
            <Button onClick={() => window.location.reload()}>Try Again</Button>
          </div>
        </div>
      </AppLayout>
    );
  }

  // -------------------- Main Report Layout --------------------
  const riskLevel = malignantRisk ? decideRiskLevel(malignantRisk.probability) : "low";

  return (
    <AppLayout>
      <div className="medical-container py-8 max-w-5xl">
        <div className="mb-6 animate-fade-in">
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-3xl font-bold mb-1">Your AI Skin Assessment</h1>
              <p className="text-muted-foreground">
                Report ID: {savedId ?? id ?? "new"} • {generatedDate.toLocaleDateString()}
              </p>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" onClick={() => setShowPreview(true)}>
                <Eye className="h-4 w-4 mr-2" />
                Preview
              </Button>
              <Button onClick={generatePDF}>
                <FileText className="h-4 w-4 mr-2" />
                Download PDF
              </Button>
            </div>
          </div>
        </div>

        {/* Disclaimer */}
        <Alert className="mb-6 border-warning bg-warning/5 animate-fade-in">
          <AlertTriangle className="h-4 w-4 text-warning" />
          <AlertDescription className="text-sm font-medium leading-relaxed">
            {professionalDisclaimer}
          </AlertDescription>
        </Alert>

        <div className="grid lg:grid-cols-3 gap-6">
          {/* Left main column */}
          <div className="lg:col-span-2 space-y-6">
            {/* Diagnosis Summary */}
            <Card className="medical-card animate-fade-in">
              <CardHeader>
                <CardTitle>Assessment Summary</CardTitle>
                <CardDescription>Most likely condition and risk indicator</CardDescription>
              </CardHeader>
              <CardContent className="grid sm:grid-cols-2 gap-4 items-center">
                <div className="space-y-1">
                  <div className="text-sm text-muted-foreground">Top condition</div>
                  <div className="text-xl font-semibold">{topDisplay}</div>
                </div>
                {malignantRisk && (
                  <div className="text-center">
                    <div
                      className={`text-4xl font-bold ${
                        riskLevel === "high"
                          ? "text-red-600"
                          : riskLevel === "moderate"
                          ? "text-amber-600"
                          : "text-green-600"
                      }`}
                    >
                      {formatPercent(malignantRisk.probability, 1)}
                    </div>
                    <Badge variant={riskBadgeVariant(riskLevel)} className="capitalize mt-1">
                      {riskLevel} risk
                    </Badge>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Patient Basics */}
            <Card className="medical-card animate-fade-in">
              <CardHeader>
                <CardTitle>Patient</CardTitle>
                <CardDescription>Essential details</CardDescription>
              </CardHeader>
              <CardContent className="grid md:grid-cols-2 gap-x-8 gap-y-3 text-sm">
                <div>
                  <span className="text-muted-foreground">Full Name:</span>{" "}
                  <span className="font-medium">{profile?.full_name || "Not provided"}</span>
                </div>
                <div>
                  <span className="text-muted-foreground">Age:</span>{" "}
                  <span className="font-medium">{profile?.age ?? "Not provided"}</span>
                </div>
                <div className="md:col-span-2">
                  <span className="text-muted-foreground">Allergies:</span>{" "}
                  <span className="font-medium">{profile?.allergies || "None reported"}</span>
                </div>
                <div>
                  <span className="text-muted-foreground">Image file:</span>{" "}
                  <span className="font-medium">{imageMeta?.filename || "N/A"}</span>
                </div>
                <div>
                  <span className="text-muted-foreground">Captured:</span>{" "}
                  <span className="font-medium">{imageMeta?.capturedAt || "N/A"}</span>
                </div>
              </CardContent>
            </Card>

            {/* Top Conditions */}
            <Card className="medical-card animate-fade-in">
              <CardHeader>
                <CardTitle>Top Conditions</CardTitle>
                <CardDescription>AI confidence (higher means more likely)</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                {(showAllPreds ? predictions : predictions.slice(0, 3)).map((p, idx) => {
                  const name = getConditionName(p.label);
                  return (
                    <div key={idx} className="space-y-2 p-4 rounded-lg bg-muted/30">
                      <div className="flex justify-between items-center">
                        <div className="font-medium">{name}</div>
                        <Badge variant={idx === 0 ? "default" : "secondary"}>{formatPercent(p.confidence, 1)}</Badge>
                      </div>
                      <Progress value={p.confidence * 100} className="h-2" />
                      <p className="text-xs text-muted-foreground">{interpretConfidence(p.confidence)}</p>
                    </div>
                  );
                })}
                {predictions.length > 3 && (
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => setShowAllPreds((s) => !s)}
                    className="w-full"
                  >
                    {showAllPreds ? (
                      <>
                        <ChevronDown className="h-4 w-4 mr-2" />
                        Show less
                      </>
                    ) : (
                      <>
                        <ChevronRight className="h-4 w-4 mr-2" />
                        Show all {predictions.length}
                      </>
                    )}
                  </Button>
                )}
              </CardContent>
            </Card>

            {/* Recommended Next Steps */}
            <Card className="medical-card animate-fade-in">
              <CardHeader>
                <CardTitle>What to do next</CardTitle>
                <CardDescription>Simple, safe guidance</CardDescription>
              </CardHeader>
              <CardContent className="space-y-3 text-sm">
                <div className="flex items-start gap-3 p-3 rounded-md bg-blue-50 dark:bg-blue-950/20">
                  <CheckCircle className="h-5 w-5 text-blue-600 flex-shrink-0 mt-0.5" />
                  <p>Visit a licensed dermatologist for clinical evaluation.</p>
                </div>
                <div className="flex items-start gap-3 p-3 rounded-md bg-purple-50 dark:bg-purple-950/20">
                  <Info className="h-5 w-5 text-purple-600 flex-shrink-0 mt-0.5" />
                  <p>Monitor the area and take periodic photos to share with your doctor.</p>
                </div>
                {riskLevel === "high" && (
                  <div className="flex items-start gap-3 p-3 rounded-md bg-red-50 dark:bg-red-950/20">
                    <AlertTriangle className="h-5 w-5 text-red-600 flex-shrink-0 mt-0.5" />
                    <p>Risk indicator is elevated — seek a prompt professional appointment.</p>
                  </div>
                )}
                <ul className="list-disc pl-6 text-xs space-y-1 text-muted-foreground">
                  <li>Do not start/stop treatment based only on this AI report.</li>
                  <li>Share allergies and medications with your clinician.</li>
                </ul>
              </CardContent>
            </Card>
          </div>

          {/* Right side column */}
          <div className="space-y-6">
            {modelInfo && (
              <Card className="medical-card animate-fade-in">
                <CardHeader>
                  <CardTitle>Model Information</CardTitle>
                  <CardDescription>Basic metadata</CardDescription>
                </CardHeader>
                <CardContent className="space-y-3 text-sm">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Source:</span>
                    <span className="font-medium">{modelInfo.architecture}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Version:</span>
                    <span className="font-medium">{modelInfo.version}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Conditions count:</span>
                    <span className="font-medium">{predictions.length || "—"}</span>
                  </div>
                  <div className="pt-2 text-xs text-muted-foreground border-t">
                    Probabilities are relative likelihood indicators, not definitive diagnoses.
                  </div>
                </CardContent>
              </Card>
            )}
            <DiseaseInfoCard info={info} loading={loadingInfo} error={errorInfo} condition={insightQuery} />
          </div>
        </div>
      </div>

      <PreviewModal />
    </AppLayout>
  );
};

export default Report;